name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 배포

jobs:
  deploy:
    runs-on: ubuntu-latest  # 리눅스 환경에서 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 코드 체크아웃

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Node.js 설치
      with:
        node-version: '16'
    
    - name: Set up Git
      run: |
        git config --global user.email 'hyemi7375@gmail.com'
        git config --global user.name 'hyemimi'

    - name: Install dependencies
      run: npm install --legacy-peer-deps  # 의존성 설치

    - name: Build the React app
      run: npm run build  # React 앱 빌드

    - name: Deploy to GitHub Pages
      run: npm run deploy  # GitHub Pages에 배포
      env:
        CI: false  # CI 환경에서 배포 시 GitHub Pages가 정상적으로 작동하도록 설정
